# Generated by Django 2.0.1 on 2018-02-05 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='schema://adress:port/(path)')),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('base.lib.applicationservers.wildfly11.Wildfly11', 'Wildfly11')], max_length=50)),
                ('lastScanned', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(max_length=50)),
                ('artifactid', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('sha1', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('groupid', 'artifactid', 'version'),
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtimeName', models.CharField(max_length=200, null=True)),
                ('detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicationServer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ApplicationServer')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='schema://adress:port/(path)')),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('base.lib.repositories.nexus.RepoNexus', 'RepoNexus')], max_length=50)),
                ('lastScanned', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Repository'),
        ),
    ]
