# Generated by Django 2.0.1 on 2018-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='schema://adress:port/(path)')),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('base.lib.applicationservers.wildfly11.Wildfly11', 'Wildfly11')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(help_text='schema://adress:port/(path)'),
        ),
    ]
