# Generated by Django 2.0.1 on 2018-01-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180119_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artifacts',
            new_name='Artifact',
        ),
    ]
