# Generated by Django 2.0.1 on 2018-01-20 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180119_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationserver',
            name='lastScanned',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 12, 19, 30, 933739, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='repository',
            name='lastScanned',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 12, 19, 30, 910224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='detected',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 12, 19, 30, 935241, tzinfo=utc)),
        ),
    ]
