# Generated by Django 2.0.1 on 2018-01-20 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180120_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationserver',
            name='lastScanned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='detected',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='repository',
            name='lastScanned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
