# Generated by Django 2.0.1 on 2018-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180120_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationserver',
            name='lastScanned',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='lastScanned',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
